from datetime import datetime
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field


class RecommendationItem(BaseModel):
    category: str = Field(..., description="Item category (e.g. Lighting, Furniture, Food, Venue, Earring)")
    name: str = Field(..., description="Suggested product or vendor name")
    description: str = Field(..., description="Concise description of the item")
    estimated_price: float = Field(..., ge=0, description="Estimated price in currency units")
    platform: str = Field(..., description="Suggested platform/vendor (e.g. IKEA, Amazon, Swiggy, Tanishq)")
    reason: str = Field(..., description="Explanation of why this matches the user request and budget")
    external_search_query: Optional[str] = Field(None, description="Suggested search term for external marketplaces")


class BudgetSummary(BaseModel):
    total_budget: float = Field(..., ge=0)
    allocated: float = Field(..., ge=0)
    remaining: float = Field(..., ge=0)
    allocation_percentage: float = Field(..., ge=0, le=100)


class RecommendationResponse(BaseModel):
    planner_type: str = Field(..., description="'home', 'party', or 'jewelry'")
    budget: float = Field(..., ge=0)
    budget_summary: BudgetSummary
    recommendations: List[RecommendationItem] = Field(default_factory=list)
    tips: List[str] = Field(default_factory=list)
    is_fallback: bool = Field(False, description="True if generated by local fallback engine instead of live Gemini")
    disclaimer: str = Field(
        default="AI-generated recommendation based on budget constraints. External platform names are search suggestions; verify live availability and prices before ordering."
    )
    metadata: Optional[Dict[str, Any]] = None


class HistoryItemResponse(BaseModel):
    id: int
    user_id: int
    planner_type: str
    request_data: Dict[str, Any]
    response_data: Dict[str, Any]
    created_at: datetime

    class Config:
        from_attributes = True


class HistoryListResponse(BaseModel):
    total_count: int
    items: List[HistoryItemResponse]
